-- #3138: the managed config keys renamed once (paths, no unit suffix);
-- minutes and hours become seconds. An override already under the new
-- name wins: the old row is dropped rather than renamed onto it.
DELETE FROM `config_overrides` WHERE `key` = 'tickets.default_priority' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.defaults.priority' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.defaults.priority' WHERE `key` = 'tickets.default_priority';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.auto_broadcast_new' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.defaults.broadcast_new' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.defaults.broadcast_new' WHERE `key` = 'tickets.auto_broadcast_new';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.summary_until_max' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.rules.summary_max' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.rules.summary_max' WHERE `key` = 'tickets.summary_until_max';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.require_then' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.rules.require_then' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.rules.require_then' WHERE `key` = 'tickets.require_then';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.require_commits' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.rules.require_commits' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.rules.require_commits' WHERE `key` = 'tickets.require_commits';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.step_stale_hours' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.steps.stale' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.steps.stale', `value` = CAST(CAST(ROUND(CAST(`value` AS REAL) * 3600) AS INTEGER) AS TEXT) WHERE `key` = 'tickets.step_stale_hours';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.step_hot_minutes' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.steps.hot' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.steps.hot', `value` = CAST(CAST(ROUND(CAST(`value` AS REAL) * 60) AS INTEGER) AS TEXT) WHERE `key` = 'tickets.step_hot_minutes';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.step_after_max_minutes' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.steps.max_wait' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.steps.max_wait', `value` = CAST(CAST(ROUND(CAST(`value` AS REAL) * 60) AS INTEGER) AS TEXT) WHERE `key` = 'tickets.step_after_max_minutes';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.wait_credit_enabled' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.wait_credit.enabled' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.wait_credit.enabled' WHERE `key` = 'tickets.wait_credit_enabled';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.wait_credit_refund' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.wait_credit.refund' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.wait_credit.refund' WHERE `key` = 'tickets.wait_credit_refund';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.wait_credit_start_minutes' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.wait_credit.start' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.wait_credit.start', `value` = CAST(CAST(ROUND(CAST(`value` AS REAL) * 60) AS INTEGER) AS TEXT) WHERE `key` = 'tickets.wait_credit_start_minutes';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.wait_credit_max_minutes' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.wait_credit.max' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.wait_credit.max', `value` = CAST(CAST(ROUND(CAST(`value` AS REAL) * 60) AS INTEGER) AS TEXT) WHERE `key` = 'tickets.wait_credit_max_minutes';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.step_min_wait_minutes' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.wait_credit.floor' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.wait_credit.floor', `value` = CAST(CAST(ROUND(CAST(`value` AS REAL) * 60) AS INTEGER) AS TEXT) WHERE `key` = 'tickets.step_min_wait_minutes';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.wait_credit_resolved_minutes' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.wait_credit.earn.resolved' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.wait_credit.earn.resolved', `value` = CAST(CAST(ROUND(CAST(`value` AS REAL) * 60) AS INTEGER) AS TEXT) WHERE `key` = 'tickets.wait_credit_resolved_minutes';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.wait_credit_resolved_no_commit_minutes' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.wait_credit.earn.resolved_no_commit' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.wait_credit.earn.resolved_no_commit', `value` = CAST(CAST(ROUND(CAST(`value` AS REAL) * 60) AS INTEGER) AS TEXT) WHERE `key` = 'tickets.wait_credit_resolved_no_commit_minutes';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.wait_credit_wontfix_minutes' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.wait_credit.earn.wontfix' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.wait_credit.earn.wontfix', `value` = CAST(CAST(ROUND(CAST(`value` AS REAL) * 60) AS INTEGER) AS TEXT) WHERE `key` = 'tickets.wait_credit_wontfix_minutes';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.wait_credit_commit_max_age_hours' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.wait_credit.earn.commit_max_age' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.wait_credit.earn.commit_max_age', `value` = CAST(CAST(ROUND(CAST(`value` AS REAL) * 3600) AS INTEGER) AS TEXT) WHERE `key` = 'tickets.wait_credit_commit_max_age_hours';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.wait_credit_max_commits_per_comment' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.wait_credit.earn.commits_per_comment' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.wait_credit.earn.commits_per_comment' WHERE `key` = 'tickets.wait_credit_max_commits_per_comment';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.wait_credit_commit_lines_per_minute' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.wait_credit.earn.lines_per_minute' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.wait_credit.earn.lines_per_minute' WHERE `key` = 'tickets.wait_credit_commit_lines_per_minute';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.wait_credit_commit_max_minutes' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.wait_credit.earn.commit_max' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.wait_credit.earn.commit_max', `value` = CAST(CAST(ROUND(CAST(`value` AS REAL) * 60) AS INTEGER) AS TEXT) WHERE `key` = 'tickets.wait_credit_commit_max_minutes';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.wait_credit_commit_min_minutes' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.wait_credit.earn.commit_min' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.wait_credit.earn.commit_min', `value` = CAST(CAST(ROUND(CAST(`value` AS REAL) * 60) AS INTEGER) AS TEXT) WHERE `key` = 'tickets.wait_credit_commit_min_minutes';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.claim_protect_minutes' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.backlog.claim_protect' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.backlog.claim_protect', `value` = CAST(CAST(ROUND(CAST(`value` AS REAL) * 60) AS INTEGER) AS TEXT) WHERE `key` = 'tickets.claim_protect_minutes';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.blocked_cooldown_multiplier' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.backlog.blocked_multiplier' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.backlog.blocked_multiplier' WHERE `key` = 'tickets.blocked_cooldown_multiplier';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'tickets.sink_then_continue_minutes' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'tickets.backlog.after_step' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'tickets.backlog.after_step', `value` = CAST(CAST(ROUND(CAST(`value` AS REAL) * 60) AS INTEGER) AS TEXT) WHERE `key` = 'tickets.sink_then_continue_minutes';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'autopoll.throttle_seconds' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'autopoll.throttle' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'autopoll.throttle' WHERE `key` = 'autopoll.throttle_seconds';--> statement-breakpoint
DELETE FROM `config_overrides` WHERE `key` = 'autopoll.include_recent_tickets' AND EXISTS (SELECT 1 FROM `config_overrides` n WHERE n.`key` = 'autopoll.recent_tickets' AND n.`project` = `config_overrides`.`project`);--> statement-breakpoint
UPDATE `config_overrides` SET `key` = 'autopoll.recent_tickets' WHERE `key` = 'autopoll.include_recent_tickets';
