/**
 * #1567 phase 2 — the generated systemd unit.
 *
 * `renderUnit` is the half of `aiball install --service` worth pinning: the
 * write path just puts this string on disk, and getting ExecStart wrong is the
 * failure that only shows up at the user's next login.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { renderUnit } from "./install.js";

test("ExecStart points at the packaged daemon entrypoint, not a tsx invocation", () => {
    const unit = renderUnit({ root: "/opt/aiball" });
    assert.match(unit, /^ExecStart=\/opt\/aiball\/bin\/aiball-daemon$/m);
    // The old unit hardcoded `npx --no-install tsx …/src/daemon.ts`, which only
    // resolves inside a checkout with dev dependencies installed.
    assert.doesNotMatch(unit, /npx/);
});

test("providers come up with the daemon, and never fail the unit", () => {
    const unit = renderUnit({ root: "/opt/aiball" });
    assert.match(unit, /^ExecStartPost=-\/opt\/aiball\/bin\/aiball providers up$/m);
});

test("host and port default, and are overridable", () => {
    const dflt = renderUnit({ root: "/opt/aiball" });
    assert.match(dflt, /^Environment=AIBALL_HOST=127\.0\.0\.1$/m);
    assert.match(dflt, /^Environment=AIBALL_PORT=7777$/m);

    const custom = renderUnit({ root: "/opt/aiball", host: "0.0.0.0", port: "7878" });
    assert.match(custom, /^Environment=AIBALL_HOST=0\.0\.0\.0$/m);
    assert.match(custom, /^Environment=AIBALL_PORT=7878$/m);
});

test("the unit announces itself as generated, so a refresh can tell it apart", () => {
    // The install path only overwrites silently when it recognises its own
    // header; a hand-written unit gets a warning first.
    assert.ok(renderUnit({ root: "/opt/aiball" }).startsWith("# Generated by `aiball install --service`"));
});
