/**
 * `aiball install --service` (#1567 phase 2) — adopt the daemon as a background
 * service.
 *
 * Installing the package only lets you **try** aiball: you run the daemon in a
 * terminal and stop it with ^C. This command is the separate, explicit gesture
 * that **adopts** it — a unit that comes back at login and after a crash. The
 * two stay apart on purpose: installing a package must never quietly register a
 * background service on someone's machine.
 *
 * The unit is *generated* from the resolved install root rather than copied
 * from `systemd/aiball.service`, because that template hardcodes the
 * `~/.local/lib/aiball` layout `install.sh` produces — a package installed by
 * npm lives wherever npm put it. Everything else (ExecStartPost bringing the
 * remote-access providers up, Restart policy, the HOST/PORT environment) is
 * lifted from that template rather than reinvented, so both paths produce a
 * daemon that behaves the same.
 *
 * On Windows the same gesture registers a **logon scheduled task** plus the
 * tray (#1571). The shape is lifted from `install.ps1` rather than reinvented —
 * same task name, same launcher files, same `%LOCALAPPDATA%\aiball` location —
 * so a box adopted by either path looks identical, and the tray's own watchdog
 * (which reads `daemon-launcher.vbs` from that directory) keeps working.
 */
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, posix as pathPosix, resolve, win32 as pathWin32 } from "node:path";
import { fileURLToPath } from "node:url";
import type { Command } from "commander";

const SERVICE_NAME = "aiball.service";
/** Scheduled-task name — must match install.ps1's `$TaskName`. */
const TASK_NAME = "aiball-daemon";

/** src/cli/install.ts → up 2 = install root. */
function installRoot(): string {
    return resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
}

function systemdUserDir(): string {
    const xdg = process.env.XDG_CONFIG_HOME;
    return join(xdg && xdg.trim() ? xdg : join(homedir(), ".config"), "systemd", "user");
}

export interface UnitOptions {
    root: string;
    host?: string;
    port?: string;
}

/**
 * Render the unit. Pure — takes the resolved paths, returns the text — so the
 * shape can be asserted without writing to anyone's systemd directory.
 */
export function renderUnit(opts: UnitOptions): string {
    // A systemd unit always carries POSIX paths, whatever host renders it —
    // plain `join` follows the RUNNING platform, so on Windows this emitted
    // `ExecStart=\opt\aiball\…` and the pinning tests failed on that lane.
    const daemon = pathPosix.join(opts.root, "bin", "aiball-daemon");
    const cli = pathPosix.join(opts.root, "bin", "aiball");
    return [
        "# Generated by `aiball install --service`. Re-run that command to update it;",
        "# hand edits are overwritten.",
        "[Unit]",
        "Description=aiball — inter-agent ticket BAL daemon",
        "After=network.target",
        "",
        "[Service]",
        "Type=simple",
        `WorkingDirectory=${opts.root}`,
        `ExecStart=${daemon}`,
        "# Bring up enabled+autostart remote-access providers (tailscale, …) with the",
        "# daemon. No-op when no `providers:` block is configured. The leading `-`",
        "# means this never fails the unit.",
        `ExecStartPost=-${cli} providers up`,
        "Restart=on-failure",
        "RestartSec=2",
        `Environment=AIBALL_HOST=${opts.host ?? "127.0.0.1"}`,
        `Environment=AIBALL_PORT=${opts.port ?? "7777"}`,
        "",
        "[Install]",
        "WantedBy=default.target",
        "",
    ].join("\n");
}

function run(cmd: string, args: string[]): boolean {
    return spawnSync(cmd, args, { stdio: "inherit" }).status === 0;
}

// =====================================================================
// Windows — logon scheduled task (#1571)
// =====================================================================

/**
 * Where install.ps1 puts the generated launchers and the daemon log in a
 * per-user install (`$LogDir`). The tray reads `daemon-launcher.vbs` from this
 * exact path, so writing ours here is what lets a package-installed daemon be
 * supervised by an already-running tray.
 */
function winLocalDir(): string {
    const local = process.env.LOCALAPPDATA;
    return join(local && local.trim() ? local : join(homedir(), "AppData", "Local"), "aiball");
}

export interface LauncherOptions {
    root: string;
    logFile: string;
    host?: string;
    port?: string;
}

/**
 * The `.cmd` a scheduled task actually runs. Two things it does that a bare
 * `ExecStart` equivalent cannot: scheduled tasks capture no stdout, so both
 * streams are appended to a log file; and that log needs a roll guard or it
 * grows without bound. Both behaviours are install.ps1's, kept identical.
 *
 * Unlike install.ps1 this calls `bin\aiball-daemon` rather than
 * `npx.cmd --no-install tsx src\daemon.ts` — that indirection is exactly what
 * the packaging work removed, and it only ever resolved inside a checkout with
 * dev dependencies present.
 *
 * Pure, like `renderUnit`: it returns text so the shape can be asserted without
 * writing to anyone's profile. CRLF because cmd.exe wants it.
 */
export function renderDaemonLauncherCmd(opts: LauncherOptions): string {
    // Mirror of `renderUnit`'s posix join: this file is always consumed by
    // cmd.exe, so it always carries Windows separators — including when the
    // Linux lane renders it to assert its shape.
    const daemon = pathWin32.join(opts.root, "bin", "aiball-daemon");
    return [
        "@echo off",
        "setlocal EnableExtensions",
        "",
        "REM Generated by `aiball install --service`. Re-run that command to update it;",
        "REM hand edits are overwritten. Redirects stdout+stderr into the log file and",
        "REM rolls it past 8MB.",
        "",
        `set "LOG=${opts.logFile}"`,
        `set "LIB=${opts.root}"`,
        "",
        'cd /d "%LIB%"',
        "",
        'if exist "%LOG%" (',
        '    for %%I in ("%LOG%") do if %%~zI GTR 8388608 (',
        '        if exist "%LOG%.1" del "%LOG%.1"',
        '        move /y "%LOG%" "%LOG%.1" >nul',
        "    )",
        ")",
        "",
        `set "AIBALL_PORT=${opts.port ?? "7777"}"`,
        `set "AIBALL_HOST=${opts.host ?? "127.0.0.1"}"`,
        "",
        `echo [%date% %time%] launching aiball daemon (port ${opts.port ?? "7777"}) >> "%LOG%"`,
        `node "${daemon}" >> "%LOG%" 2>&1`,
        "",
    ].join("\r\n");
}

/**
 * `cmd.exe /c <file>.cmd` flashes a console window when a scheduled task fires
 * at logon. wscript + a one-line .vbs whose third `Run` argument is 0 (SW_HIDE)
 * is the classic way around it — same trick, same reason, as install.ps1.
 */
export function renderHiddenLauncherVbs(targetCmd: string): string {
    return [
        "' Generated by `aiball install --service`. Runs the launcher with no",
        "' visible console window (the third Run argument, 0, is SW_HIDE).",
        `CreateObject("WScript.Shell").Run "cmd /c """ & "${targetCmd}" & """", 0, False`,
        "",
    ].join("\r\n");
}

/**
 * Register the logon task. Settings mirror install.ps1 exactly: start when
 * available, five restarts a minute apart, no execution time limit, run as the
 * interactive user at Limited level (never elevated — adopting a daemon must
 * not silently gain privileges).
 */
function registerLogonTask(target: string, description: string, dryRun: boolean): boolean {
    const ps = [
        `$action = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument '"${target}"'`,
        "$trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME",
        "$settings = New-ScheduledTaskSettingsSet -StartWhenAvailable -RestartCount 5" +
            " -RestartInterval (New-TimeSpan -Minutes 1) -ExecutionTimeLimit (New-TimeSpan -Hours 0)",
        "$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME" +
            " -LogonType Interactive -RunLevel Limited",
        `Register-ScheduledTask -TaskName '${TASK_NAME}' -Action $action -Trigger $trigger` +
            ` -Settings $settings -Principal $principal -Description '${description}' -Force | Out-Null`,
    ].join("; ");
    if (dryRun) {
        process.stdout.write(`# powershell -NoProfile -Command\n${ps}\n`);
        return true;
    }
    return run("powershell", ["-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", ps]);
}

interface WinTaskOptions {
    remove?: boolean;
    host?: string;
    port?: string;
    dryRun?: boolean;
    tray?: boolean;
}

/**
 * The Windows half of `--service`: a logon scheduled task named like
 * install.ps1's, driving the same generated launchers in the same directory.
 *
 * Default is tray-owns-the-daemon, matching install.ps1: the task starts the
 * tray, the tray starts and supervises the daemon, so "icon visible = aiball
 * running". `--no-tray` registers the daemon launcher directly for a headless
 * box. Either way both launcher files are written, because the tray's watchdog
 * looks for `daemon-launcher.vbs` whether or not it owns the task.
 */
function installWindowsTask(opts: WinTaskOptions): void {
    const root = installRoot();
    const dir = winLocalDir();
    const cmdPath = join(dir, "daemon-launcher.cmd");
    const vbsPath = join(dir, "daemon-launcher.vbs");
    const trayVbsPath = join(dir, "tray-launcher.vbs");
    const trayCmd = join(root, "bin", "aiball-tray.cmd");
    const useTray = opts.tray !== false;

    if (opts.remove) {
        if (opts.dryRun) {
            process.stdout.write(
                `would unregister scheduled task ${TASK_NAME} and delete:\n` +
                    `  ${cmdPath}\n  ${vbsPath}\n  ${trayVbsPath}\n`,
            );
            return;
        }
        run("powershell", [
            "-NoProfile",
            "-ExecutionPolicy",
            "Bypass",
            "-Command",
            `if (Get-ScheduledTask -TaskName '${TASK_NAME}' -ErrorAction SilentlyContinue) {` +
                ` try { Stop-ScheduledTask -TaskName '${TASK_NAME}' -ErrorAction Stop } catch { };` +
                ` Unregister-ScheduledTask -TaskName '${TASK_NAME}' -Confirm:$false }`,
        ]);
        for (const f of [cmdPath, vbsPath, trayVbsPath]) rmSync(f, { force: true });
        process.stdout.write(`removed scheduled task ${TASK_NAME} and its launchers\n`);
        return;
    }

    if (useTray && !existsSync(trayCmd)) {
        process.stderr.write(
            `tray launcher missing: ${trayCmd}\n` +
                "Pass --no-tray to register the daemon directly instead.\n",
        );
        process.exitCode = 1;
        return;
    }

    const logFile = join(dir, "daemon.log");
    const launcher = renderDaemonLauncherCmd({ root, logFile, host: opts.host, port: opts.port });
    const target = useTray ? trayVbsPath : vbsPath;
    const description = useTray
        ? `aiball — the tray owns the daemon; closing the tray stops aiball. Logs to ${logFile}.`
        : `aiball daemon (headless). Logs to ${logFile}.`;

    if (opts.dryRun) {
        process.stdout.write(`# ${cmdPath}\n${launcher}\n`);
        process.stdout.write(`# ${vbsPath}\n${renderHiddenLauncherVbs(cmdPath)}\n`);
        if (useTray) {
            process.stdout.write(`# ${trayVbsPath}\n${renderHiddenLauncherVbs(trayCmd)}\n`);
        }
        registerLogonTask(target, description, true);
        return;
    }

    mkdirSync(dir, { recursive: true });
    writeFileSync(cmdPath, launcher);
    writeFileSync(vbsPath, renderHiddenLauncherVbs(cmdPath));
    if (useTray) writeFileSync(trayVbsPath, renderHiddenLauncherVbs(trayCmd));
    process.stdout.write(`wrote ${cmdPath}\n`);

    if (!registerLogonTask(target, description, false)) {
        process.stderr.write(`Register-ScheduledTask ${TASK_NAME} failed — launchers written but no task\n`);
        process.exitCode = 1;
        return;
    }
    process.stdout.write(
        `aiball is now a scheduled task: it starts at logon${useTray ? " (via the tray)" : ""}.\n` +
            `  Get-ScheduledTask -TaskName ${TASK_NAME}\n` +
            `  Start-ScheduledTask -TaskName ${TASK_NAME}\n` +
            `  aiball install --service --remove   # to give it back\n`,
    );
}

export function registerInstallCommands(program: Command): void {
    program
        .command("install")
        .description(
            "Adopt aiball as a background service (systemd user unit on Linux, logon scheduled task on Windows). Installing the package alone does not register anything — this is the explicit opt-in.",
        )
        .option("--service", "Install (or refresh) the user service unit")
        .option("--remove", "Remove the service unit instead of installing it")
        .option("--host <host>", "Listen host baked into the unit (default 127.0.0.1)")
        .option("--port <port>", "Listen port baked into the unit (default 7777)")
        .option("--dry-run", "Print the unit that would be written, change nothing")
        .option(
            "--no-tray",
            "Windows only: register the daemon directly instead of letting the tray own it",
        )
        .action(
            (opts: {
                service?: boolean;
                remove?: boolean;
                host?: string;
                port?: string;
                dryRun?: boolean;
                tray?: boolean;
            }) => {
                if (!opts.service) {
                    process.stderr.write(
                        "nothing to do — pass --service to install the background service.\n" +
                            "  aiball install --service            # adopt: start at login, restart on crash\n" +
                            "  aiball install --service --remove   # give it back\n",
                    );
                    process.exitCode = 1;
                    return;
                }

                if (process.platform === "win32") {
                    installWindowsTask(opts);
                    return;
                }

                if (process.platform !== "linux") {
                    process.stderr.write(
                        `--service adopts the daemon as a systemd user unit (Linux) or a logon\n` +
                            `scheduled task (Windows); this platform (${process.platform}) has neither.\n`,
                    );
                    process.exitCode = 1;
                    return;
                }

                const dir = systemdUserDir();
                const unitPath = join(dir, SERVICE_NAME);

                if (opts.remove) {
                    if (!existsSync(unitPath)) {
                        process.stdout.write(`no unit at ${unitPath} — nothing to remove\n`);
                        return;
                    }
                    if (opts.dryRun) {
                        process.stdout.write(`would stop, disable and delete ${unitPath}\n`);
                        return;
                    }
                    run("systemctl", ["--user", "disable", "--now", SERVICE_NAME]);
                    rmSync(unitPath, { force: true });
                    run("systemctl", ["--user", "daemon-reload"]);
                    process.stdout.write(`removed ${unitPath}\n`);
                    return;
                }

                const unit = renderUnit({ root: installRoot(), host: opts.host, port: opts.port });

                if (opts.dryRun) {
                    process.stdout.write(`# ${unitPath}\n${unit}`);
                    return;
                }

                // A hand-edited unit is worth naming before we overwrite it —
                // silently replacing someone's tweaks is how a "convenience"
                // command loses trust.
                if (existsSync(unitPath)) {
                    const current = readFileSync(unitPath, "utf8");
                    if (current === unit) {
                        process.stdout.write(`${unitPath} already up to date\n`);
                    } else if (!current.startsWith("# Generated by `aiball install --service`")) {
                        process.stdout.write(
                            `note: replacing a unit that was not generated by this command (${unitPath})\n`,
                        );
                    }
                }

                mkdirSync(dir, { recursive: true });
                writeFileSync(unitPath, unit);
                process.stdout.write(`wrote ${unitPath}\n`);

                if (!run("systemctl", ["--user", "daemon-reload"])) {
                    process.stderr.write("systemctl --user daemon-reload failed — unit written but not loaded\n");
                    process.exitCode = 1;
                    return;
                }
                if (!run("systemctl", ["--user", "enable", "--now", SERVICE_NAME])) {
                    process.stderr.write(`systemctl --user enable --now ${SERVICE_NAME} failed\n`);
                    process.exitCode = 1;
                    return;
                }
                process.stdout.write(
                    `aiball is now a service: it starts at login and restarts on failure.\n` +
                        `  systemctl --user status ${SERVICE_NAME}\n` +
                        `  aiball install --service --remove   # to give it back\n`,
                );
            },
        );
}
