/**
 * #1567 phase 2 — the generated systemd unit.
 *
 * `renderUnit` is the half of `aiball install --service` worth pinning: the
 * write path just puts this string on disk, and getting ExecStart wrong is the
 * failure that only shows up at the user's next login.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { renderDaemonLauncherCmd, renderHiddenLauncherVbs, renderUnit } from "./install.js";

test("ExecStart points at the packaged daemon entrypoint, not a tsx invocation", () => {
    const unit = renderUnit({ root: "/opt/aiball" });
    assert.match(unit, /^ExecStart=\/opt\/aiball\/bin\/aiball-daemon$/m);
    // The old unit hardcoded `npx --no-install tsx …/src/daemon.ts`, which only
    // resolves inside a checkout with dev dependencies installed.
    assert.doesNotMatch(unit, /npx/);
});

test("providers come up with the daemon, and never fail the unit", () => {
    const unit = renderUnit({ root: "/opt/aiball" });
    assert.match(unit, /^ExecStartPost=-\/opt\/aiball\/bin\/aiball providers up$/m);
});

test("host and port default, and are overridable", () => {
    const dflt = renderUnit({ root: "/opt/aiball" });
    assert.match(dflt, /^Environment=AIBALL_HOST=127\.0\.0\.1$/m);
    assert.match(dflt, /^Environment=AIBALL_PORT=7777$/m);

    const custom = renderUnit({ root: "/opt/aiball", host: "0.0.0.0", port: "7878" });
    assert.match(custom, /^Environment=AIBALL_HOST=0\.0\.0\.0$/m);
    assert.match(custom, /^Environment=AIBALL_PORT=7878$/m);
});

test("the unit announces itself as generated, so a refresh can tell it apart", () => {
    // The install path only overwrites silently when it recognises its own
    // header; a hand-written unit gets a warning first.
    assert.ok(renderUnit({ root: "/opt/aiball" }).startsWith("# Generated by `aiball install --service`"));
});

// =====================================================================
// #1571 — the Windows half: scheduled-task launchers
// =====================================================================

const WIN = { root: "C:\\aiball", logFile: "C:\\logs\\daemon.log" };

test("the launcher runs the packaged daemon entrypoint, not a tsx invocation", () => {
    const cmd = renderDaemonLauncherCmd(WIN);
    assert.match(cmd, /^node "C:\\aiball\\bin\\aiball-daemon" >> "%LOG%" 2>&1$/m);
    // install.ps1 ran `npx.cmd --no-install tsx src\daemon.ts`, which only
    // resolves inside a checkout with dev dependencies — the same indirection
    // the systemd unit shed.
    assert.doesNotMatch(cmd, /npx/);
    assert.doesNotMatch(cmd, /tsx/);
});

test("the launcher rolls its log, because a scheduled task captures no stdout", () => {
    const cmd = renderDaemonLauncherCmd(WIN);
    assert.match(cmd, /%%~zI GTR 8388608/);
    assert.match(cmd, /move \/y "%LOG%" "%LOG%\.1"/);
});

test("cmd.exe needs CRLF, and host/port default and override like the unit", () => {
    const dflt = renderDaemonLauncherCmd(WIN);
    assert.ok(dflt.includes("\r\n"), "a LF-only .cmd is not reliably parsed by cmd.exe");
    assert.match(dflt, /^set "AIBALL_PORT=7777"$/m);
    assert.match(dflt, /^set "AIBALL_HOST=127\.0\.0\.1"$/m);

    const custom = renderDaemonLauncherCmd({ ...WIN, host: "0.0.0.0", port: "7878" });
    assert.match(custom, /^set "AIBALL_PORT=7878"$/m);
    assert.match(custom, /^set "AIBALL_HOST=0\.0\.0\.0"$/m);
});

test("the vbs wrapper hides the console window at logon", () => {
    // The third Run argument is SW_HIDE. Without it the task flashes a console
    // every login — the reason install.ps1 goes through wscript at all.
    assert.match(renderHiddenLauncherVbs("C:\\logs\\x.cmd"), /", 0, False$/m);
});

test("both generated Windows files announce themselves, like the unit", () => {
    assert.match(renderDaemonLauncherCmd(WIN), /Generated by `aiball install --service`/);
    assert.match(renderHiddenLauncherVbs("C:\\logs\\x.cmd"), /Generated by `aiball install --service`/);
});
