/**
 * `aiball install --service` (#1567 phase 2) — adopt the daemon as a background
 * service.
 *
 * Installing the package only lets you **try** aiball: you run the daemon in a
 * terminal and stop it with ^C. This command is the separate, explicit gesture
 * that **adopts** it — a unit that comes back at login and after a crash. The
 * two stay apart on purpose: installing a package must never quietly register a
 * background service on someone's machine.
 *
 * The unit is *generated* from the resolved install root rather than copied
 * from `systemd/aiball.service`, because that template hardcodes the
 * `~/.local/lib/aiball` layout `install.sh` produces — a package installed by
 * npm lives wherever npm put it. Everything else (ExecStartPost bringing the
 * remote-access providers up, Restart policy, the HOST/PORT environment) is
 * lifted from that template rather than reinvented, so both paths produce a
 * daemon that behaves the same.
 *
 * Linux only for now: the Windows equivalent is a logon scheduled task plus the
 * tray, which `install.ps1` already knows how to create.
 */
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { Command } from "commander";

const SERVICE_NAME = "aiball.service";

/** src/cli/install.ts → up 2 = install root. */
function installRoot(): string {
    return resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
}

function systemdUserDir(): string {
    const xdg = process.env.XDG_CONFIG_HOME;
    return join(xdg && xdg.trim() ? xdg : join(homedir(), ".config"), "systemd", "user");
}

export interface UnitOptions {
    root: string;
    host?: string;
    port?: string;
}

/**
 * Render the unit. Pure — takes the resolved paths, returns the text — so the
 * shape can be asserted without writing to anyone's systemd directory.
 */
export function renderUnit(opts: UnitOptions): string {
    const daemon = join(opts.root, "bin", "aiball-daemon");
    const cli = join(opts.root, "bin", "aiball");
    return [
        "# Generated by `aiball install --service`. Re-run that command to update it;",
        "# hand edits are overwritten.",
        "[Unit]",
        "Description=aiball — inter-agent ticket BAL daemon",
        "After=network.target",
        "",
        "[Service]",
        "Type=simple",
        `WorkingDirectory=${opts.root}`,
        `ExecStart=${daemon}`,
        "# Bring up enabled+autostart remote-access providers (tailscale, …) with the",
        "# daemon. No-op when no `providers:` block is configured. The leading `-`",
        "# means this never fails the unit.",
        `ExecStartPost=-${cli} providers up`,
        "Restart=on-failure",
        "RestartSec=2",
        `Environment=AIBALL_HOST=${opts.host ?? "127.0.0.1"}`,
        `Environment=AIBALL_PORT=${opts.port ?? "7777"}`,
        "",
        "[Install]",
        "WantedBy=default.target",
        "",
    ].join("\n");
}

function run(cmd: string, args: string[]): boolean {
    return spawnSync(cmd, args, { stdio: "inherit" }).status === 0;
}

export function registerInstallCommands(program: Command): void {
    program
        .command("install")
        .description(
            "Adopt aiball as a background service (systemd user unit on Linux). Installing the package alone does not register anything — this is the explicit opt-in.",
        )
        .option("--service", "Install (or refresh) the user service unit")
        .option("--remove", "Remove the service unit instead of installing it")
        .option("--host <host>", "Listen host baked into the unit (default 127.0.0.1)")
        .option("--port <port>", "Listen port baked into the unit (default 7777)")
        .option("--dry-run", "Print the unit that would be written, change nothing")
        .action(
            (opts: {
                service?: boolean;
                remove?: boolean;
                host?: string;
                port?: string;
                dryRun?: boolean;
            }) => {
                if (!opts.service) {
                    process.stderr.write(
                        "nothing to do — pass --service to install the background service.\n" +
                            "  aiball install --service            # adopt: start at login, restart on crash\n" +
                            "  aiball install --service --remove   # give it back\n",
                    );
                    process.exitCode = 1;
                    return;
                }

                if (process.platform !== "linux") {
                    process.stderr.write(
                        `--service installs a systemd user unit, which this platform (${process.platform}) does not have.\n` +
                            "On Windows the equivalent is a logon scheduled task plus the tray — use install.ps1 for now.\n",
                    );
                    process.exitCode = 1;
                    return;
                }

                const dir = systemdUserDir();
                const unitPath = join(dir, SERVICE_NAME);

                if (opts.remove) {
                    if (!existsSync(unitPath)) {
                        process.stdout.write(`no unit at ${unitPath} — nothing to remove\n`);
                        return;
                    }
                    if (opts.dryRun) {
                        process.stdout.write(`would stop, disable and delete ${unitPath}\n`);
                        return;
                    }
                    run("systemctl", ["--user", "disable", "--now", SERVICE_NAME]);
                    rmSync(unitPath, { force: true });
                    run("systemctl", ["--user", "daemon-reload"]);
                    process.stdout.write(`removed ${unitPath}\n`);
                    return;
                }

                const unit = renderUnit({ root: installRoot(), host: opts.host, port: opts.port });

                if (opts.dryRun) {
                    process.stdout.write(`# ${unitPath}\n${unit}`);
                    return;
                }

                // A hand-edited unit is worth naming before we overwrite it —
                // silently replacing someone's tweaks is how a "convenience"
                // command loses trust.
                if (existsSync(unitPath)) {
                    const current = readFileSync(unitPath, "utf8");
                    if (current === unit) {
                        process.stdout.write(`${unitPath} already up to date\n`);
                    } else if (!current.startsWith("# Generated by `aiball install --service`")) {
                        process.stdout.write(
                            `note: replacing a unit that was not generated by this command (${unitPath})\n`,
                        );
                    }
                }

                mkdirSync(dir, { recursive: true });
                writeFileSync(unitPath, unit);
                process.stdout.write(`wrote ${unitPath}\n`);

                if (!run("systemctl", ["--user", "daemon-reload"])) {
                    process.stderr.write("systemctl --user daemon-reload failed — unit written but not loaded\n");
                    process.exitCode = 1;
                    return;
                }
                if (!run("systemctl", ["--user", "enable", "--now", SERVICE_NAME])) {
                    process.stderr.write(`systemctl --user enable --now ${SERVICE_NAME} failed\n`);
                    process.exitCode = 1;
                    return;
                }
                process.stdout.write(
                    `aiball is now a service: it starts at login and restarts on failure.\n` +
                        `  systemctl --user status ${SERVICE_NAME}\n` +
                        `  aiball install --service --remove   # to give it back\n`,
                );
            },
        );
}
