/**
 * Token registry (#B.94). Three kinds share the same table:
 *   - `install` — one-shot, generated by install.sh, consumed by /setup.
 *   - `auth`    — long-lived, issued by /setup or /login (humans web).
 *   - `agent`   — long-lived, issued via `aiball token issue` (CLI/MCP).
 *
 * The bearer-token middleware (src/auth.ts) does one lookup per
 * request to resolve `token → {consumer_id, kind}`. Install tokens
 * are rejected for /api/* — they grant access to /setup only.
 */
import { and, asc, eq, lt } from "drizzle-orm";
import { randomBytes } from "node:crypto";
import * as schema from "../schema.js";
import { getDb, nowIso } from "./connection.js";

export type TokenKind = "install" | "auth" | "agent";

export interface Token {
    token: string;
    consumer_id: string | null;
    kind: TokenKind;
    label: string | null;
    created_at: string;
    last_used_at: string | null;
    expires_at: string | null;
}

function rowToToken(r: schema.Token): Token {
    return {
        token: r.token,
        consumer_id: r.consumerId,
        kind: (r.kind as TokenKind) ?? "agent",
        label: r.label,
        created_at: r.createdAt,
        last_used_at: r.lastUsedAt,
        expires_at: r.expiresAt,
    };
}

/**
 * Generate a fresh token string. Format: `aiball-<48 hex>` so it's
 * immediately recognizable in logs / accidental commits.
 */
export function generateTokenString(): string {
    return `aiball-${randomBytes(24).toString("hex")}`;
}

export interface IssueTokenInput {
    consumer_id?: string | null;
    kind: TokenKind;
    label?: string | null;
    /** ISO8601 timestamp. NULL = no expiry. */
    expires_at?: string | null;
}

export function issueToken(input: IssueTokenInput): Token {
    const token = generateTokenString();
    const now = nowIso();
    getDb().insert(schema.tokens).values({
        token,
        consumerId: input.consumer_id ?? null,
        kind: input.kind,
        label: input.label ?? null,
        createdAt: now,
        expiresAt: input.expires_at ?? null,
    }).run();
    return {
        token,
        consumer_id: input.consumer_id ?? null,
        kind: input.kind,
        label: input.label ?? null,
        created_at: now,
        last_used_at: null,
        expires_at: input.expires_at ?? null,
    };
}

/**
 * Resolve a bearer-token to its row. Bumps `last_used_at` on success.
 * Returns null when the token doesn't exist OR has expired.
 */
export function getTokenAndTouch(token: string): Token | null {
    if (!token) return null;
    const r = getDb().select().from(schema.tokens)
        .where(eq(schema.tokens.token, token))
        .get();
    if (!r) return null;
    const now = nowIso();
    if (r.expiresAt && r.expiresAt <= now) {
        // Expired; clean up lazily.
        getDb().delete(schema.tokens).where(eq(schema.tokens.token, token)).run();
        return null;
    }
    getDb().update(schema.tokens)
        .set({ lastUsedAt: now })
        .where(eq(schema.tokens.token, token))
        .run();
    return rowToToken({ ...r, lastUsedAt: now });
}

/** Read-only lookup, doesn't touch `last_used_at`. */
export function getToken(token: string): Token | null {
    if (!token) return null;
    const r = getDb().select().from(schema.tokens)
        .where(eq(schema.tokens.token, token))
        .get();
    if (!r) return null;
    const now = nowIso();
    if (r.expiresAt && r.expiresAt <= now) return null;
    return rowToToken(r);
}

export function deleteToken(token: string): boolean {
    if (!token) return false;
    const r = getDb().delete(schema.tokens)
        .where(eq(schema.tokens.token, token))
        .run();
    return r.changes > 0;
}

export function listTokens(opts: { kind?: TokenKind; consumer_id?: string } = {}): Token[] {
    let q = getDb().select().from(schema.tokens).$dynamic();
    const conds = [];
    if (opts.kind) conds.push(eq(schema.tokens.kind, opts.kind));
    if (opts.consumer_id) conds.push(eq(schema.tokens.consumerId, opts.consumer_id));
    if (conds.length) q = q.where(and(...conds));
    return q.orderBy(asc(schema.tokens.createdAt)).all().map(rowToToken);
}

/**
 * Delete all expired tokens. Called at boot + periodically to keep
 * the table tidy. Not security-critical (getTokenAndTouch already
 * filters expired rows out lazily).
 */
export function purgeExpiredTokens(): number {
    const r = getDb().delete(schema.tokens)
        .where(lt(schema.tokens.expiresAt, nowIso()))
        .run();
    return r.changes;
}

/**
 * Convenience: any auth/agent token currently valid in the DB? Used
 * by install.sh to decide whether to also create a default human or
 * just print the existing setup URL.
 */
export function anyHumanCredentials(): boolean {
    const r = getDb().select({ token: schema.tokens.token })
        .from(schema.tokens)
        .where(eq(schema.tokens.kind, "auth"))
        .get();
    return !!r;
}
