/**
 * #3489 — the conversations Claude Code keeps for a folder: listed most recent
 * first with the first thing the user typed, `latest` and an id checked
 * against the folder, and the picked one winning over the recorded one.
 */
import { test, after } from "node:test";
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, rmSync, utimesSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { claudeProjectDir, firstPrompt, latestConversation, listConversations, pickConversation } from "./claude-conversations.js";
import { resolveSession } from "./session-id.js";

const home = mkdtempSync("/tmp/aiball-3489-");
after(() => rmSync(home, { recursive: true, force: true }));
const cwd = "/work/my_project";
const dir = claudeProjectDir(cwd, home);
mkdirSync(dir, { recursive: true });

const OLD = "11111111-1111-4111-8111-111111111111";
const NEW = "22222222-2222-4222-8222-222222222222";
const line = (o: object) => JSON.stringify(o);
const user = (content: unknown, extra: object = {}) => line({ type: "user", message: { role: "user", content }, ...extra });

/** A transcript as Claude Code writes one: what is not the user's own words comes first. */
writeFileSync(join(dir, `${OLD}.jsonl`), [
    line({ type: "summary", summary: "x" }),
    user("Caveat: The messages below were generated by the user while running local commands.", { isMeta: true }),
    user("<command-name>/model</command-name>"),
    user("<local-command-stdout>Set model</local-command-stdout>"),
    user([{ type: "tool_result", content: "ok" }]),
    user("  fix   the\nlogin bug  "),
    user("second prompt"),
].join("\n"));
writeFileSync(join(dir, `${NEW}.jsonl`), [user([{ type: "text", text: "x".repeat(300) }]), "{\"type\":\"user\",\"mess"].join("\n"));
writeFileSync(join(dir, "not-a-conversation.jsonl"), user("ignored"));
utimesSync(join(dir, `${OLD}.jsonl`), new Date("2026-10-01T10:00:00Z"), new Date("2026-10-01T10:00:00Z"));
utimesSync(join(dir, `${NEW}.jsonl`), new Date("2026-10-02T10:00:00Z"), new Date("2026-10-02T10:00:00Z"));

test("the first prompt is the user's own words: no meta, no command, no tool result; spaces folded", () => {
    assert.equal(firstPrompt(join(dir, `${OLD}.jsonl`)), "fix the login bug");
    const cut = firstPrompt(join(dir, `${NEW}.jsonl`))!;
    assert.equal(cut.length, 120, "cut to 120");
    assert.ok(cut.endsWith("…"));
    assert.equal(firstPrompt(join(dir, "missing.jsonl")), null);
});

test("listed most recent first, only uuid-named transcripts, at most limit", () => {
    const list = listConversations(cwd, 20, home);
    assert.deepEqual(list.map((c) => c.id), [NEW, OLD]);
    assert.equal(list[1]!.updated_at, "2026-10-01T10:00:00.000Z");
    assert.equal(listConversations(cwd, 1, home).length, 1);
    assert.deepEqual(listConversations("/elsewhere", 20, home), [], "a folder without conversations");
    assert.equal(latestConversation(cwd, home), NEW);
});

test("latest, or an id of the folder; anything else is refused with why", () => {
    assert.deepEqual(pickConversation(cwd, "latest", home), { id: NEW });
    assert.deepEqual(pickConversation(cwd, OLD.toUpperCase(), home), { id: OLD });
    assert.match((pickConversation(cwd, "33333333-3333-4333-8333-333333333333", home) as { error: string }).error, /no conversation/);
    assert.match((pickConversation(cwd, "nope", home) as { error: string }).error, /not a conversation id/);
    assert.match((pickConversation("/elsewhere", "latest", home) as { error: string }).error, /no conversation in/);
});

test("the picked conversation wins over the recorded one", () => {
    const plan = resolveSession({ mode: "auto", configuredId: "", loopName: "cl-x", sessionExists: () => true, readPersistedId: () => NEW, pick: OLD });
    assert.deepEqual([plan.sessionId, plan.args], [OLD, ["--resume", OLD]]);
    const recorded = resolveSession({ mode: "auto", configuredId: "", loopName: "cl-x", sessionExists: () => true, readPersistedId: () => NEW });
    assert.equal(recorded.sessionId, NEW, "without a pick, as before");
});
