import { createApp } from "vue";
import PrimeVue from "primevue/config";
import Aura from "@primeuix/themes/aura";
import ToastService from "primevue/toastservice";
import ConfirmationService from "primevue/confirmationservice";

import "primeicons/primeicons.css";
import "./style.css";
// #B.196 Layer 0: dark-mode overrides extracted from per-component <style>
// blocks. Loaded after base styles so .aiball-dark .X overrides win on
// specificity (0,2,0 vs 0,1,0). Regenerated by scripts/extract-theme-dark.mjs.
import "./styles/theme-dark.css";

import App from "./App.vue";

const app = createApp(App);
app.use(PrimeVue, {
    theme: {
        preset: Aura,
        options: { darkModeSelector: ".aiball-dark" },
    },
});
app.use(ToastService);
app.use(ConfirmationService);
app.mount("#app");
